using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using System.Linq.Expressions;
namespace EnumConstantConverter
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        string name;
        [DllImport("user32.dll")]
        public static extern uint MapVirtualKey(uint uCode, uint uMapType);
        private void Form1_Load(object sender, EventArgs e)
        {
            ushort S_LBUTTON = (ushort)MapVirtualKey(0x01, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LBUTTON);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LBUTTON.ToString() + ",\r\n");
            ushort S_RBUTTON = (ushort)MapVirtualKey(0x02, 0);
            name = MemberInfoGetting.GetMemberName(() => S_RBUTTON);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_RBUTTON.ToString() + ",\r\n");
            ushort S_CANCEL = (ushort)MapVirtualKey(0x03, 0);
            name = MemberInfoGetting.GetMemberName(() => S_CANCEL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_CANCEL.ToString() + ",\r\n");
            ushort S_MBUTTON = (ushort)MapVirtualKey(0x04, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MBUTTON);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MBUTTON.ToString() + ",\r\n");
            ushort S_XBUTTON1 = (ushort)MapVirtualKey(0x05, 0);
            name = MemberInfoGetting.GetMemberName(() => S_XBUTTON1);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_XBUTTON1.ToString() + ",\r\n");
            ushort S_XBUTTON2 = (ushort)MapVirtualKey(0x06, 0);
            name = MemberInfoGetting.GetMemberName(() => S_XBUTTON2);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_XBUTTON2.ToString() + ",\r\n");
            ushort S_BACK = (ushort)MapVirtualKey(0x08, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BACK);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BACK.ToString() + ",\r\n");
            ushort S_Tab = (ushort)MapVirtualKey(0x09, 0);
            name = MemberInfoGetting.GetMemberName(() => S_Tab);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_Tab.ToString() + ",\r\n");
            ushort S_CLEAR = (ushort)MapVirtualKey(0x0C, 0);
            name = MemberInfoGetting.GetMemberName(() => S_CLEAR);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_CLEAR.ToString() + ",\r\n");
            ushort S_Return = (ushort)MapVirtualKey(0x0D, 0);
            name = MemberInfoGetting.GetMemberName(() => S_Return);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_Return.ToString() + ",\r\n");
            ushort S_SHIFT = (ushort)MapVirtualKey(0x10, 0);
            name = MemberInfoGetting.GetMemberName(() => S_SHIFT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_SHIFT.ToString() + ",\r\n");
            ushort S_CONTROL = (ushort)MapVirtualKey(0x11, 0);
            name = MemberInfoGetting.GetMemberName(() => S_CONTROL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_CONTROL.ToString() + ",\r\n");
            ushort S_MENU = (ushort)MapVirtualKey(0x12, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MENU);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MENU.ToString() + ",\r\n");
            ushort S_PAUSE = (ushort)MapVirtualKey(0x13, 0);
            name = MemberInfoGetting.GetMemberName(() => S_PAUSE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_PAUSE.ToString() + ",\r\n");
            ushort S_CAPITAL = (ushort)MapVirtualKey(0x14, 0);
            name = MemberInfoGetting.GetMemberName(() => S_CAPITAL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_CAPITAL.ToString() + ",\r\n");
            ushort S_KANA = (ushort)MapVirtualKey(0x15, 0);
            name = MemberInfoGetting.GetMemberName(() => S_KANA);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_KANA.ToString() + ",\r\n");
            ushort S_HANGEUL = (ushort)MapVirtualKey(0x15, 0);
            name = MemberInfoGetting.GetMemberName(() => S_HANGEUL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_HANGEUL.ToString() + ",\r\n");
            ushort S_HANGUL = (ushort)MapVirtualKey(0x15, 0);
            name = MemberInfoGetting.GetMemberName(() => S_HANGUL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_HANGUL.ToString() + ",\r\n");
            ushort S_JUNJA = (ushort)MapVirtualKey(0x17, 0);
            name = MemberInfoGetting.GetMemberName(() => S_JUNJA);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_JUNJA.ToString() + ",\r\n");
            ushort S_FINAL = (ushort)MapVirtualKey(0x18, 0);
            name = MemberInfoGetting.GetMemberName(() => S_FINAL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_FINAL.ToString() + ",\r\n");
            ushort S_HANJA = (ushort)MapVirtualKey(0x19, 0);
            name = MemberInfoGetting.GetMemberName(() => S_HANJA);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_HANJA.ToString() + ",\r\n");
            ushort S_KANJI = (ushort)MapVirtualKey(0x19, 0);
            name = MemberInfoGetting.GetMemberName(() => S_KANJI);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_KANJI.ToString() + ",\r\n");
            ushort S_Escape = (ushort)MapVirtualKey(0x1B, 0);
            name = MemberInfoGetting.GetMemberName(() => S_Escape);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_Escape.ToString() + ",\r\n");
            ushort S_CONVERT = (ushort)MapVirtualKey(0x1C, 0);
            name = MemberInfoGetting.GetMemberName(() => S_CONVERT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_CONVERT.ToString() + ",\r\n");
            ushort S_NONCONVERT = (ushort)MapVirtualKey(0x1D, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NONCONVERT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NONCONVERT.ToString() + ",\r\n");
            ushort S_ACCEPT = (ushort)MapVirtualKey(0x1E, 0);
            name = MemberInfoGetting.GetMemberName(() => S_ACCEPT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_ACCEPT.ToString() + ",\r\n");
            ushort S_MODECHANGE = (ushort)MapVirtualKey(0x1F, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MODECHANGE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MODECHANGE.ToString() + ",\r\n");
            ushort S_Space = (ushort)MapVirtualKey(0x20, 0);
            name = MemberInfoGetting.GetMemberName(() => S_Space);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_Space.ToString() + ",\r\n");
            ushort S_PRIOR = (ushort)MapVirtualKey(0x21, 0);
            name = MemberInfoGetting.GetMemberName(() => S_PRIOR);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_PRIOR.ToString() + ",\r\n");
            ushort S_NEXT = (ushort)MapVirtualKey(0x22, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NEXT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NEXT.ToString() + ",\r\n");
            ushort S_END = (ushort)MapVirtualKey(0x23, 0);
            name = MemberInfoGetting.GetMemberName(() => S_END);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_END.ToString() + ",\r\n");
            ushort S_HOME = (ushort)MapVirtualKey(0x24, 0);
            name = MemberInfoGetting.GetMemberName(() => S_HOME);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_HOME.ToString() + ",\r\n");
            ushort S_LEFT = (ushort)MapVirtualKey(0x25, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LEFT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LEFT.ToString() + ",\r\n");
            ushort S_UP = (ushort)MapVirtualKey(0x26, 0);
            name = MemberInfoGetting.GetMemberName(() => S_UP);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_UP.ToString() + ",\r\n");
            ushort S_RIGHT = (ushort)MapVirtualKey(0x27, 0);
            name = MemberInfoGetting.GetMemberName(() => S_RIGHT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_RIGHT.ToString() + ",\r\n");
            ushort S_DOWN = (ushort)MapVirtualKey(0x28, 0);
            name = MemberInfoGetting.GetMemberName(() => S_DOWN);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_DOWN.ToString() + ",\r\n");
            ushort S_SELECT = (ushort)MapVirtualKey(0x29, 0);
            name = MemberInfoGetting.GetMemberName(() => S_SELECT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_SELECT.ToString() + ",\r\n");
            ushort S_PRINT = (ushort)MapVirtualKey(0x2A, 0);
            name = MemberInfoGetting.GetMemberName(() => S_PRINT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_PRINT.ToString() + ",\r\n");
            ushort S_EXECUTE = (ushort)MapVirtualKey(0x2B, 0);
            name = MemberInfoGetting.GetMemberName(() => S_EXECUTE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_EXECUTE.ToString() + ",\r\n");
            ushort S_SNAPSHOT = (ushort)MapVirtualKey(0x2C, 0);
            name = MemberInfoGetting.GetMemberName(() => S_SNAPSHOT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_SNAPSHOT.ToString() + ",\r\n");
            ushort S_INSERT = (ushort)MapVirtualKey(0x2D, 0);
            name = MemberInfoGetting.GetMemberName(() => S_INSERT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_INSERT.ToString() + ",\r\n");
            ushort S_DELETE = (ushort)MapVirtualKey(0x2E, 0);
            name = MemberInfoGetting.GetMemberName(() => S_DELETE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_DELETE.ToString() + ",\r\n");
            ushort S_HELP = (ushort)MapVirtualKey(0x2F, 0);
            name = MemberInfoGetting.GetMemberName(() => S_HELP);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_HELP.ToString() + ",\r\n");
            ushort S_APOSTROPHE = (ushort)MapVirtualKey(0xDE, 0);
            name = MemberInfoGetting.GetMemberName(() => S_APOSTROPHE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_APOSTROPHE.ToString() + ",\r\n");
            ushort S_0 = (ushort)MapVirtualKey(0x30, 0);
            name = MemberInfoGetting.GetMemberName(() => S_0);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_0.ToString() + ",\r\n");
            ushort S_1 = (ushort)MapVirtualKey(0x31, 0);
            name = MemberInfoGetting.GetMemberName(() => S_1);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_1.ToString() + ",\r\n");
            ushort S_2 = (ushort)MapVirtualKey(0x32, 0);
            name = MemberInfoGetting.GetMemberName(() => S_2);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_2.ToString() + ",\r\n");
            ushort S_3 = (ushort)MapVirtualKey(0x33, 0);
            name = MemberInfoGetting.GetMemberName(() => S_3);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_3.ToString() + ",\r\n");
            ushort S_4 = (ushort)MapVirtualKey(0x34, 0);
            name = MemberInfoGetting.GetMemberName(() => S_4);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_4.ToString() + ",\r\n");
            ushort S_5 = (ushort)MapVirtualKey(0x35, 0);
            name = MemberInfoGetting.GetMemberName(() => S_5);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_5.ToString() + ",\r\n");
            ushort S_6 = (ushort)MapVirtualKey(0x36, 0);
            name = MemberInfoGetting.GetMemberName(() => S_6);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_6.ToString() + ",\r\n");
            ushort S_7 = (ushort)MapVirtualKey(0x37, 0);
            name = MemberInfoGetting.GetMemberName(() => S_7);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_7.ToString() + ",\r\n");
            ushort S_8 = (ushort)MapVirtualKey(0x38, 0);
            name = MemberInfoGetting.GetMemberName(() => S_8);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_8.ToString() + ",\r\n");
            ushort S_9 = (ushort)MapVirtualKey(0x39, 0);
            name = MemberInfoGetting.GetMemberName(() => S_9);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_9.ToString() + ",\r\n");
            ushort S_A = (ushort)MapVirtualKey(0x41, 0);
            name = MemberInfoGetting.GetMemberName(() => S_A);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_A.ToString() + ",\r\n");
            ushort S_B = (ushort)MapVirtualKey(0x42, 0);
            name = MemberInfoGetting.GetMemberName(() => S_B);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_B.ToString() + ",\r\n");
            ushort S_C = (ushort)MapVirtualKey(0x43, 0);
            name = MemberInfoGetting.GetMemberName(() => S_C);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_C.ToString() + ",\r\n");
            ushort S_D = (ushort)MapVirtualKey(0x44, 0);
            name = MemberInfoGetting.GetMemberName(() => S_D);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_D.ToString() + ",\r\n");
            ushort S_E = (ushort)MapVirtualKey(0x45, 0);
            name = MemberInfoGetting.GetMemberName(() => S_E);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_E.ToString() + ",\r\n");
            ushort S_F = (ushort)MapVirtualKey(0x46, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F.ToString() + ",\r\n");
            ushort S_G = (ushort)MapVirtualKey(0x47, 0);
            name = MemberInfoGetting.GetMemberName(() => S_G);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_G.ToString() + ",\r\n");
            ushort S_H = (ushort)MapVirtualKey(0x48, 0);
            name = MemberInfoGetting.GetMemberName(() => S_H);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_H.ToString() + ",\r\n");
            ushort S_I = (ushort)MapVirtualKey(0x49, 0);
            name = MemberInfoGetting.GetMemberName(() => S_I);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_I.ToString() + ",\r\n");
            ushort S_J = (ushort)MapVirtualKey(0x4A, 0);
            name = MemberInfoGetting.GetMemberName(() => S_J);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_J.ToString() + ",\r\n");
            ushort S_K = (ushort)MapVirtualKey(0x4B, 0);
            name = MemberInfoGetting.GetMemberName(() => S_K);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_K.ToString() + ",\r\n");
            ushort S_L = (ushort)MapVirtualKey(0x4C, 0);
            name = MemberInfoGetting.GetMemberName(() => S_L);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_L.ToString() + ",\r\n");
            ushort S_M = (ushort)MapVirtualKey(0x4D, 0);
            name = MemberInfoGetting.GetMemberName(() => S_M);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_M.ToString() + ",\r\n");
            ushort S_N = (ushort)MapVirtualKey(0x4E, 0);
            name = MemberInfoGetting.GetMemberName(() => S_N);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_N.ToString() + ",\r\n");
            ushort S_O = (ushort)MapVirtualKey(0x4F, 0);
            name = MemberInfoGetting.GetMemberName(() => S_O);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_O.ToString() + ",\r\n");
            ushort S_P = (ushort)MapVirtualKey(0x50, 0);
            name = MemberInfoGetting.GetMemberName(() => S_P);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_P.ToString() + ",\r\n");
            ushort S_Q = (ushort)MapVirtualKey(0x51, 0);
            name = MemberInfoGetting.GetMemberName(() => S_Q);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_Q.ToString() + ",\r\n");
            ushort S_R = (ushort)MapVirtualKey(0x52, 0);
            name = MemberInfoGetting.GetMemberName(() => S_R);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_R.ToString() + ",\r\n");
            ushort S_S = (ushort)MapVirtualKey(0x53, 0);
            name = MemberInfoGetting.GetMemberName(() => S_S);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_S.ToString() + ",\r\n");
            ushort S_T = (ushort)MapVirtualKey(0x54, 0);
            name = MemberInfoGetting.GetMemberName(() => S_T);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_T.ToString() + ",\r\n");
            ushort S_U = (ushort)MapVirtualKey(0x55, 0);
            name = MemberInfoGetting.GetMemberName(() => S_U);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_U.ToString() + ",\r\n");
            ushort S_V = (ushort)MapVirtualKey(0x56, 0);
            name = MemberInfoGetting.GetMemberName(() => S_V);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_V.ToString() + ",\r\n");
            ushort S_W = (ushort)MapVirtualKey(0x57, 0);
            name = MemberInfoGetting.GetMemberName(() => S_W);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_W.ToString() + ",\r\n");
            ushort S_X = (ushort)MapVirtualKey(0x58, 0);
            name = MemberInfoGetting.GetMemberName(() => S_X);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_X.ToString() + ",\r\n");
            ushort S_Y = (ushort)MapVirtualKey(0x59, 0);
            name = MemberInfoGetting.GetMemberName(() => S_Y);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_Y.ToString() + ",\r\n");
            ushort S_Z = (ushort)MapVirtualKey(0x5A, 0);
            name = MemberInfoGetting.GetMemberName(() => S_Z);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_Z.ToString() + ",\r\n");
            ushort S_LWIN = (ushort)MapVirtualKey(0x5B, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LWIN);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LWIN.ToString() + ",\r\n");
            ushort S_RWIN = (ushort)MapVirtualKey(0x5C, 0);
            name = MemberInfoGetting.GetMemberName(() => S_RWIN);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_RWIN.ToString() + ",\r\n");
            ushort S_APPS = (ushort)MapVirtualKey(0x5D, 0);
            name = MemberInfoGetting.GetMemberName(() => S_APPS);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_APPS.ToString() + ",\r\n");
            ushort S_SLEEP = (ushort)MapVirtualKey(0x5F, 0);
            name = MemberInfoGetting.GetMemberName(() => S_SLEEP);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_SLEEP.ToString() + ",\r\n");
            ushort S_NUMPAD0 = (ushort)MapVirtualKey(0x60, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD0);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD0.ToString() + ",\r\n");
            ushort S_NUMPAD1 = (ushort)MapVirtualKey(0x61, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD1);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD1.ToString() + ",\r\n");
            ushort S_NUMPAD2 = (ushort)MapVirtualKey(0x62, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD2);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD2.ToString() + ",\r\n");
            ushort S_NUMPAD3 = (ushort)MapVirtualKey(0x63, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD3);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD3.ToString() + ",\r\n");
            ushort S_NUMPAD4 = (ushort)MapVirtualKey(0x64, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD4);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD4.ToString() + ",\r\n");
            ushort S_NUMPAD5 = (ushort)MapVirtualKey(0x65, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD5);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD5.ToString() + ",\r\n");
            ushort S_NUMPAD6 = (ushort)MapVirtualKey(0x66, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD6);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD6.ToString() + ",\r\n");
            ushort S_NUMPAD7 = (ushort)MapVirtualKey(0x67, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD7);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD7.ToString() + ",\r\n");
            ushort S_NUMPAD8 = (ushort)MapVirtualKey(0x68, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD8);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD8.ToString() + ",\r\n");
            ushort S_NUMPAD9 = (ushort)MapVirtualKey(0x69, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMPAD9);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMPAD9.ToString() + ",\r\n");
            ushort S_MULTIPLY = (ushort)MapVirtualKey(0x6A, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MULTIPLY);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MULTIPLY.ToString() + ",\r\n");
            ushort S_ADD = (ushort)MapVirtualKey(0x6B, 0);
            name = MemberInfoGetting.GetMemberName(() => S_ADD);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_ADD.ToString() + ",\r\n");
            ushort S_SEPARATOR = (ushort)MapVirtualKey(0x6C, 0);
            name = MemberInfoGetting.GetMemberName(() => S_SEPARATOR);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_SEPARATOR.ToString() + ",\r\n");
            ushort S_SUBTRACT = (ushort)MapVirtualKey(0x6D, 0);
            name = MemberInfoGetting.GetMemberName(() => S_SUBTRACT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_SUBTRACT.ToString() + ",\r\n");
            ushort S_DECIMAL = (ushort)MapVirtualKey(0x6E, 0);
            name = MemberInfoGetting.GetMemberName(() => S_DECIMAL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_DECIMAL.ToString() + ",\r\n");
            ushort S_DIVIDE = (ushort)MapVirtualKey(0x6F, 0);
            name = MemberInfoGetting.GetMemberName(() => S_DIVIDE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_DIVIDE.ToString() + ",\r\n");
            ushort S_F1 = (ushort)MapVirtualKey(0x70, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F1);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F1.ToString() + ",\r\n");
            ushort S_F2 = (ushort)MapVirtualKey(0x71, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F2);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F2.ToString() + ",\r\n");
            ushort S_F3 = (ushort)MapVirtualKey(0x72, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F3);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F3.ToString() + ",\r\n");
            ushort S_F4 = (ushort)MapVirtualKey(0x73, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F4);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F4.ToString() + ",\r\n");
            ushort S_F5 = (ushort)MapVirtualKey(0x74, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F5);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F5.ToString() + ",\r\n");
            ushort S_F6 = (ushort)MapVirtualKey(0x75, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F6);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F6.ToString() + ",\r\n");
            ushort S_F7 = (ushort)MapVirtualKey(0x76, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F7);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F7.ToString() + ",\r\n");
            ushort S_F8 = (ushort)MapVirtualKey(0x77, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F8);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F8.ToString() + ",\r\n");
            ushort S_F9 = (ushort)MapVirtualKey(0x78, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F9);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F9.ToString() + ",\r\n");
            ushort S_F10 = (ushort)MapVirtualKey(0x79, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F10);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F10.ToString() + ",\r\n");
            ushort S_F11 = (ushort)MapVirtualKey(0x7A, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F11);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F11.ToString() + ",\r\n");
            ushort S_F12 = (ushort)MapVirtualKey(0x7B, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F12);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F12.ToString() + ",\r\n");
            ushort S_F13 = (ushort)MapVirtualKey(0x7C, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F13);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F13.ToString() + ",\r\n");
            ushort S_F14 = (ushort)MapVirtualKey(0x7D, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F14);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F14.ToString() + ",\r\n");
            ushort S_F15 = (ushort)MapVirtualKey(0x7E, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F15);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F15.ToString() + ",\r\n");
            ushort S_F16 = (ushort)MapVirtualKey(0x7F, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F16);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F16.ToString() + ",\r\n");
            ushort S_F17 = (ushort)MapVirtualKey(0x80, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F17);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F17.ToString() + ",\r\n");
            ushort S_F18 = (ushort)MapVirtualKey(0x81, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F18);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F18.ToString() + ",\r\n");
            ushort S_F19 = (ushort)MapVirtualKey(0x82, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F19);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F19.ToString() + ",\r\n");
            ushort S_F20 = (ushort)MapVirtualKey(0x83, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F20);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F20.ToString() + ",\r\n");
            ushort S_F21 = (ushort)MapVirtualKey(0x84, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F21);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F21.ToString() + ",\r\n");
            ushort S_F22 = (ushort)MapVirtualKey(0x85, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F22);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F22.ToString() + ",\r\n");
            ushort S_F23 = (ushort)MapVirtualKey(0x86, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F23);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F23.ToString() + ",\r\n");
            ushort S_F24 = (ushort)MapVirtualKey(0x87, 0);
            name = MemberInfoGetting.GetMemberName(() => S_F24);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_F24.ToString() + ",\r\n");
            ushort S_NUMLOCK = (ushort)MapVirtualKey(0x90, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NUMLOCK);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NUMLOCK.ToString() + ",\r\n");
            ushort S_SCROLL = (ushort)MapVirtualKey(0x91, 0);
            name = MemberInfoGetting.GetMemberName(() => S_SCROLL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_SCROLL.ToString() + ",\r\n");
            ushort S_LeftShift = (ushort)MapVirtualKey(0xA0, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LeftShift);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LeftShift.ToString() + ",\r\n");
            ushort S_RightShift = (ushort)MapVirtualKey(0xA1, 0);
            name = MemberInfoGetting.GetMemberName(() => S_RightShift);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_RightShift.ToString() + ",\r\n");
            ushort S_LeftControl = (ushort)MapVirtualKey(0xA2, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LeftControl);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LeftControl.ToString() + ",\r\n");
            ushort S_RightControl = (ushort)MapVirtualKey(0xA3, 0);
            name = MemberInfoGetting.GetMemberName(() => S_RightControl);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_RightControl.ToString() + ",\r\n");
            ushort S_LMENU = (ushort)MapVirtualKey(0xA4, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LMENU);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LMENU.ToString() + ",\r\n");
            ushort S_RMENU = (ushort)MapVirtualKey(0xA5, 0);
            name = MemberInfoGetting.GetMemberName(() => S_RMENU);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_RMENU.ToString() + ",\r\n");
            ushort S_BROWSER_BACK = (ushort)MapVirtualKey(0xA6, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BROWSER_BACK);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BROWSER_BACK.ToString() + ",\r\n");
            ushort S_BROWSER_FORWARD = (ushort)MapVirtualKey(0xA7, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BROWSER_FORWARD);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BROWSER_FORWARD.ToString() + ",\r\n");
            ushort S_BROWSER_REFRESH = (ushort)MapVirtualKey(0xA8, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BROWSER_REFRESH);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BROWSER_REFRESH.ToString() + ",\r\n");
            ushort S_BROWSER_STOP = (ushort)MapVirtualKey(0xA9, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BROWSER_STOP);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BROWSER_STOP.ToString() + ",\r\n");
            ushort S_BROWSER_SEARCH = (ushort)MapVirtualKey(0xAA, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BROWSER_SEARCH);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BROWSER_SEARCH.ToString() + ",\r\n");
            ushort S_BROWSER_FAVORITES = (ushort)MapVirtualKey(0xAB, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BROWSER_FAVORITES);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BROWSER_FAVORITES.ToString() + ",\r\n");
            ushort S_BROWSER_HOME = (ushort)MapVirtualKey(0xAC, 0);
            name = MemberInfoGetting.GetMemberName(() => S_BROWSER_HOME);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_BROWSER_HOME.ToString() + ",\r\n");
            ushort S_VOLUME_MUTE = (ushort)MapVirtualKey(0xAD, 0);
            name = MemberInfoGetting.GetMemberName(() => S_VOLUME_MUTE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_VOLUME_MUTE.ToString() + ",\r\n");
            ushort S_VOLUME_DOWN = (ushort)MapVirtualKey(0xAE, 0);
            name = MemberInfoGetting.GetMemberName(() => S_VOLUME_DOWN);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_VOLUME_DOWN.ToString() + ",\r\n");
            ushort S_VOLUME_UP = (ushort)MapVirtualKey(0xAF, 0);
            name = MemberInfoGetting.GetMemberName(() => S_VOLUME_UP);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_VOLUME_UP.ToString() + ",\r\n");
            ushort S_MEDIA_NEXT_TRACK = (ushort)MapVirtualKey(0xB0, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MEDIA_NEXT_TRACK);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MEDIA_NEXT_TRACK.ToString() + ",\r\n");
            ushort S_MEDIA_PREV_TRACK = (ushort)MapVirtualKey(0xB1, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MEDIA_PREV_TRACK);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MEDIA_PREV_TRACK.ToString() + ",\r\n");
            ushort S_MEDIA_STOP = (ushort)MapVirtualKey(0xB2, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MEDIA_STOP);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MEDIA_STOP.ToString() + ",\r\n");
            ushort S_MEDIA_PLAY_PAUSE = (ushort)MapVirtualKey(0xB3, 0);
            name = MemberInfoGetting.GetMemberName(() => S_MEDIA_PLAY_PAUSE);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_MEDIA_PLAY_PAUSE.ToString() + ",\r\n");
            ushort S_LAUNCH_MAIL = (ushort)MapVirtualKey(0xB4, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LAUNCH_MAIL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LAUNCH_MAIL.ToString() + ",\r\n");
            ushort S_LAUNCH_MEDIA_SELECT = (ushort)MapVirtualKey(0xB5, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LAUNCH_MEDIA_SELECT);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LAUNCH_MEDIA_SELECT.ToString() + ",\r\n");
            ushort S_LAUNCH_APP1 = (ushort)MapVirtualKey(0xB6, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LAUNCH_APP1);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LAUNCH_APP1.ToString() + ",\r\n");
            ushort S_LAUNCH_APP2 = (ushort)MapVirtualKey(0xB7, 0);
            name = MemberInfoGetting.GetMemberName(() => S_LAUNCH_APP2);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_LAUNCH_APP2.ToString() + ",\r\n");
            ushort S_OEM_1 = (ushort)MapVirtualKey(0xBA, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_1);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_1.ToString() + ",\r\n");
            ushort S_OEM_PLUS = (ushort)MapVirtualKey(0xBB, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_PLUS);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_PLUS.ToString() + ",\r\n");
            ushort S_OEM_COMMA = (ushort)MapVirtualKey(0xBC, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_COMMA);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_COMMA.ToString() + ",\r\n");
            ushort S_OEM_MINUS = (ushort)MapVirtualKey(0xBD, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_MINUS);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_MINUS.ToString() + ",\r\n");
            ushort S_OEM_PERIOD = (ushort)MapVirtualKey(0xBE, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_PERIOD);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_PERIOD.ToString() + ",\r\n");
            ushort S_OEM_2 = (ushort)MapVirtualKey(0xBF, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_2);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_2.ToString() + ",\r\n");
            ushort S_OEM_3 = (ushort)MapVirtualKey(0xC0, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_3);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_3.ToString() + ",\r\n");
            ushort S_OEM_4 = (ushort)MapVirtualKey(0xDB, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_4);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_4.ToString() + ",\r\n");
            ushort S_OEM_5 = (ushort)MapVirtualKey(0xDC, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_5);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_5.ToString() + ",\r\n");
            ushort S_OEM_6 = (ushort)MapVirtualKey(0xDD, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_6);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_6.ToString() + ",\r\n");
            ushort S_OEM_7 = (ushort)MapVirtualKey(0xDE, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_7);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_7.ToString() + ",\r\n");
            ushort S_OEM_8 = (ushort)MapVirtualKey(0xDF, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_8);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_8.ToString() + ",\r\n");
            ushort S_OEM_102 = (ushort)MapVirtualKey(0xE2, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_102);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_102.ToString() + ",\r\n");
            ushort S_PROCESSKEY = (ushort)MapVirtualKey(0xE5, 0);
            name = MemberInfoGetting.GetMemberName(() => S_PROCESSKEY);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_PROCESSKEY.ToString() + ",\r\n");
            ushort S_PACKET = (ushort)MapVirtualKey(0xE7, 0);
            name = MemberInfoGetting.GetMemberName(() => S_PACKET);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_PACKET.ToString() + ",\r\n");
            ushort S_ATTN = (ushort)MapVirtualKey(0xF6, 0);
            name = MemberInfoGetting.GetMemberName(() => S_ATTN);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_ATTN.ToString() + ",\r\n");
            ushort S_CRSEL = (ushort)MapVirtualKey(0xF7, 0);
            name = MemberInfoGetting.GetMemberName(() => S_CRSEL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_CRSEL.ToString() + ",\r\n");
            ushort S_EXSEL = (ushort)MapVirtualKey(0xF8, 0);
            name = MemberInfoGetting.GetMemberName(() => S_EXSEL);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_EXSEL.ToString() + ",\r\n");
            ushort S_EREOF = (ushort)MapVirtualKey(0xF9, 0);
            name = MemberInfoGetting.GetMemberName(() => S_EREOF);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_EREOF.ToString() + ",\r\n");
            ushort S_PLAY = (ushort)MapVirtualKey(0xFA, 0);
            name = MemberInfoGetting.GetMemberName(() => S_PLAY);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_PLAY.ToString() + ",\r\n");
            ushort S_ZOOM = (ushort)MapVirtualKey(0xFB, 0);
            name = MemberInfoGetting.GetMemberName(() => S_ZOOM);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_ZOOM.ToString() + ",\r\n");
            ushort S_NONAME = (ushort)MapVirtualKey(0xFC, 0);
            name = MemberInfoGetting.GetMemberName(() => S_NONAME);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_NONAME.ToString() + ",\r\n");
            ushort S_PA1 = (ushort)MapVirtualKey(0xFD, 0);
            name = MemberInfoGetting.GetMemberName(() => S_PA1);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_PA1.ToString() + ",\r\n");
            ushort S_OEM_CLEAR = (ushort)MapVirtualKey(0xFE, 0);
            name = MemberInfoGetting.GetMemberName(() => S_OEM_CLEAR);
            richTextBox1.AppendText(name.Replace("S_", "").ToUpper() + " = " + S_OEM_CLEAR.ToString() + ",\r\n");
        }
        public static class MemberInfoGetting
        {
            public static string GetMemberName<T>(Expression<Func<T>> memberExpression)
            {
                MemberExpression expressionBody = (MemberExpression)memberExpression.Body;
                return expressionBody.Member.Name;
            }
        }
    }
}