using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ConfigurationFileRewriter
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        private static string line1, line2, line3, line4, line5, line6, line7, line8, line9, line10, line11, line12, line13, line14, line15, line16, line17, line18, line19, line20, line21, line22, line23, line24, line25, line26, line27, line28, line29, line30, line31, line32, line33, line34, line35, line36, line37, line38, line39, line40, line41, line42, line43, line44, line45, line46, line47, line48, line49, line50, line51, line52, line53, line54, line55, line56, line57, line58, line59, line60, line61, line62, line63, line64, line65, line66, line67, line68, line69, line70, line71, line72, line73, line74, line75, line76, line77, line78, line79, line80, line81, line82, line83, line84, line85, line86, line87, line88, line89, line90, line91, line92, line93, line94, line95, line96, line97, line98, line99, line100, line101, line102, line103, line104, line105;
        private void button1_Click(object sender, EventArgs e)
        {
            String myRead;
            System.Windows.Forms.OpenFileDialog openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            openFileDialog1.Filter = "txt files (*.txt)|*.txt|All files (*.*)|*.*";
            openFileDialog1.FilterIndex = 2;
            openFileDialog1.RestoreDirectory = true;
            if (openFileDialog1.ShowDialog() == System.Windows.Forms.DialogResult.OK)
            {
                myRead = openFileDialog1.FileName;
                System.IO.StreamReader file = new System.IO.StreamReader(myRead);
                file.ReadLine();
                file.ReadLine();
                line1 = file.ReadLine();
                file.ReadLine();
                line2 = file.ReadLine();
                file.ReadLine();
                line3 = file.ReadLine();
                file.ReadLine();
                line4 = file.ReadLine();
                file.ReadLine();
                line5 = file.ReadLine();
                file.ReadLine();
                line6 = file.ReadLine();
                file.ReadLine();
                line7 = file.ReadLine();
                file.ReadLine();
                line8 = file.ReadLine();
                file.ReadLine();
                line9 = file.ReadLine();
                file.ReadLine();
                line10 = file.ReadLine();
                file.ReadLine();
                line11 = file.ReadLine();
                file.ReadLine();
                line12 = file.ReadLine();
                file.ReadLine();
                line13 = file.ReadLine();
                file.ReadLine();
                line14 = file.ReadLine();
                file.ReadLine();
                line15 = file.ReadLine();
                file.ReadLine();
                line16 = file.ReadLine();
                file.ReadLine();
                line17 = file.ReadLine();
                file.ReadLine();
                line18 = file.ReadLine();
                file.ReadLine();
                line19 = file.ReadLine();
                file.ReadLine();
                line20 = file.ReadLine();
                file.ReadLine();
                line21 = file.ReadLine();
                file.ReadLine();
                line22 = file.ReadLine();
                file.ReadLine();
                line23 = file.ReadLine();
                file.ReadLine();
                line24 = file.ReadLine();
                file.ReadLine();
                line25 = file.ReadLine();
                file.ReadLine();
                line26 = file.ReadLine();
                file.ReadLine();
                line27 = file.ReadLine();
                file.ReadLine();
                line28 = file.ReadLine();
                file.ReadLine();
                line29 = file.ReadLine();
                file.ReadLine();
                line30 = file.ReadLine();
                file.ReadLine();
                line31 = file.ReadLine();
                file.ReadLine();
                line32 = file.ReadLine();
                file.ReadLine();
                line33 = file.ReadLine();
                file.ReadLine();
                line34 = file.ReadLine();
                file.ReadLine();
                line35 = file.ReadLine();
                file.ReadLine();
                line36 = file.ReadLine();
                file.ReadLine();
                line37 = file.ReadLine();
                file.ReadLine();
                line38 = file.ReadLine();
                file.ReadLine();
                line39 = file.ReadLine();
                file.ReadLine();
                line40 = file.ReadLine();
                file.ReadLine();
                line41 = file.ReadLine();
                file.ReadLine();
                line42 = file.ReadLine();
                file.ReadLine();
                line43 = file.ReadLine();
                file.ReadLine();
                line44 = file.ReadLine();
                file.ReadLine();
                line45 = file.ReadLine();
                file.ReadLine();
                line46 = file.ReadLine();
                file.ReadLine();
                line47 = file.ReadLine();
                file.ReadLine();
                line48 = file.ReadLine();
                file.ReadLine();
                line49 = file.ReadLine();
                file.ReadLine();
                line50 = file.ReadLine();
                file.ReadLine();
                line51 = file.ReadLine();
                file.ReadLine();
                line52 = file.ReadLine();
                file.ReadLine();
                line53 = file.ReadLine();
                file.ReadLine();
                line54 = file.ReadLine();
                file.ReadLine();
                line55 = file.ReadLine();
                file.ReadLine();
                line56 = file.ReadLine();
                file.ReadLine();
                line57 = file.ReadLine();
                file.ReadLine();
                line58 = file.ReadLine();
                file.ReadLine();
                line59 = file.ReadLine();
                file.ReadLine();
                line60 = file.ReadLine();
                file.ReadLine();
                line61 = file.ReadLine();
                file.ReadLine();
                line62 = file.ReadLine();
                file.ReadLine();
                line63 = file.ReadLine();
                file.ReadLine();
                line64 = file.ReadLine();
                file.ReadLine();
                line65 = file.ReadLine();
                file.ReadLine();
                line66 = file.ReadLine();
                file.ReadLine();
                line67 = file.ReadLine();
                file.ReadLine();
                line68 = file.ReadLine();
                file.ReadLine();
                line69 = file.ReadLine();
                file.ReadLine();
                line70 = file.ReadLine();
                file.ReadLine();
                line71 = file.ReadLine();
                file.ReadLine();
                line72 = file.ReadLine();
                file.ReadLine();
                line73 = file.ReadLine();
                file.ReadLine();
                line74 = file.ReadLine();
                file.ReadLine();
                line75 = file.ReadLine();
                file.ReadLine();
                line76 = file.ReadLine();
                file.ReadLine();
                line77 = file.ReadLine();
                file.ReadLine();
                line78 = file.ReadLine();
                file.ReadLine();
                line79 = file.ReadLine();
                file.ReadLine();
                line80 = file.ReadLine();
                file.ReadLine();
                line81 = file.ReadLine();
                file.ReadLine();
                line82 = file.ReadLine();
                file.ReadLine();
                line83 = file.ReadLine();
                file.ReadLine();
                line84 = file.ReadLine();
                file.ReadLine();
                line85 = file.ReadLine();
                file.ReadLine();
                line86 = file.ReadLine();
                file.ReadLine();
                line87 = file.ReadLine();
                file.ReadLine();
                line88 = file.ReadLine();
                file.ReadLine();
                line89 = file.ReadLine();
                file.ReadLine();
                line90 = file.ReadLine();
                file.ReadLine();
                line91 = file.ReadLine();
                file.ReadLine();
                line92 = file.ReadLine();
                file.ReadLine();
                line93 = file.ReadLine();
                file.ReadLine();
                line94 = file.ReadLine();
                file.ReadLine();
                line95 = file.ReadLine();
                file.ReadLine();
                line96 = file.ReadLine();
                file.ReadLine();
                line97 = file.ReadLine();
                file.ReadLine();
                line98 = file.ReadLine();
                file.ReadLine();
                line99 = file.ReadLine();
                file.ReadLine();
                line100 = file.ReadLine();
                file.ReadLine();
                line101 = file.ReadLine();
                file.ReadLine();
                line102 = file.ReadLine();
                file.ReadLine();
                line103 = file.ReadLine();
                file.ReadLine();
                line104 = file.ReadLine();
                file.ReadLine();
                line105 = file.ReadLine();
                file.Close();
                System.IO.StreamWriter filerewrite = new System.IO.StreamWriter(myRead);
                filerewrite.WriteLine(myRead);
                filerewrite.WriteLine("//brink");
                filerewrite.WriteLine(line1);
                filerewrite.WriteLine("//metro");
                filerewrite.WriteLine(line2);
                filerewrite.WriteLine("//titanfall");
                filerewrite.WriteLine(line3);
                filerewrite.WriteLine("//cursor");
                filerewrite.WriteLine(line4);
                filerewrite.WriteLine("//warface");
                filerewrite.WriteLine(line5);
                filerewrite.WriteLine("//bo3");
                filerewrite.WriteLine(line6);
                filerewrite.WriteLine("//fake");
                filerewrite.WriteLine(line7);
                filerewrite.WriteLine("//mw3");
                filerewrite.WriteLine(line8);
                filerewrite.WriteLine("//xaim");
                filerewrite.WriteLine(line9);
                filerewrite.WriteLine("//A press I/O");
                filerewrite.WriteLine(line10);
                filerewrite.WriteLine("//A accuracy");
                filerewrite.WriteLine(line11);
                filerewrite.WriteLine("//no roll qe");
                filerewrite.WriteLine(line12);
                filerewrite.WriteLine("//Home f only");
                filerewrite.WriteLine(line13);
                filerewrite.WriteLine("//wheel script");
                filerewrite.WriteLine(line14);
                filerewrite.WriteLine("//A view on");
                filerewrite.WriteLine(line15);
                filerewrite.WriteLine("//1 tab I/O");
                filerewrite.WriteLine(line16);
                filerewrite.WriteLine("//A aim plus");
                filerewrite.WriteLine(line17);
                filerewrite.WriteLine("//Home -> - & +");
                filerewrite.WriteLine(line18);
                filerewrite.WriteLine("//stick view");
                filerewrite.WriteLine(line19);
                filerewrite.WriteLine("//wheel view");
                filerewrite.WriteLine(line20);
                filerewrite.WriteLine("//1 and 2 view");
                filerewrite.WriteLine(line21);
                filerewrite.WriteLine("//nunchuck");
                filerewrite.WriteLine(line22);
                filerewrite.WriteLine("//rebind keys"); 
                filerewrite.WriteLine(line23);
                filerewrite.WriteLine("//lock features and options");
                filerewrite.WriteLine(line24);
                filerewrite.WriteLine("//1 B swap");
                filerewrite.WriteLine(line25);
                filerewrite.WriteLine("//A C swap");
                filerewrite.WriteLine(line26);
                filerewrite.WriteLine("//push r 1'");
                filerewrite.WriteLine(line27);
                filerewrite.WriteLine("//cancel reload x");
                filerewrite.WriteLine(line28);
                filerewrite.WriteLine("//double A r");
                filerewrite.WriteLine(line29);
                filerewrite.WriteLine("//1 tab switch");
                filerewrite.WriteLine(line30);
                filerewrite.WriteLine("//A slide A+B");
                filerewrite.WriteLine(line31);
                filerewrite.WriteLine("//dpad view");
                filerewrite.WriteLine(line32);
                filerewrite.WriteLine("//A B switch");
                filerewrite.WriteLine(line33);
                filerewrite.WriteLine("//Z press I/O");
                filerewrite.WriteLine(line34);
                filerewrite.WriteLine("//driver mouse");
                filerewrite.WriteLine(line35);
                filerewrite.WriteLine("//driver keyboard");
                filerewrite.WriteLine(line36);
                filerewrite.WriteLine("//stick arrows");
                filerewrite.WriteLine(line37);
                filerewrite.WriteLine("//A roll qe");
                filerewrite.WriteLine(line38);
                filerewrite.WriteLine("//cancel reload x");
                filerewrite.WriteLine(line39);
                filerewrite.WriteLine("//double A r");
                filerewrite.WriteLine(line40);
                filerewrite.WriteLine("//1 tab switch");
                filerewrite.WriteLine(line41);
                filerewrite.WriteLine("//nunchuck stick");
                filerewrite.WriteLine(line42);
                filerewrite.WriteLine("//wiimote alone wheel");
                filerewrite.WriteLine(line43);
                filerewrite.WriteLine("//wiimote alone up");
                filerewrite.WriteLine(line44);
                filerewrite.WriteLine("//wiimote alone down");
                filerewrite.WriteLine(line46);
                filerewrite.WriteLine("//wiimote b");
                filerewrite.WriteLine(line46);
                filerewrite.WriteLine("//wiimote a");
                filerewrite.WriteLine(line47);
                filerewrite.WriteLine("//wiimote plus");
                filerewrite.WriteLine(line48);
                filerewrite.WriteLine("//wiimote minus");
                filerewrite.WriteLine(line49);
                filerewrite.WriteLine("//wiimote alone roll left");
                filerewrite.WriteLine(line50);
                filerewrite.WriteLine("//wiimote alone home");
                filerewrite.WriteLine(line51);
                filerewrite.WriteLine("//wiimote alone a and b");
                filerewrite.WriteLine(line52);
                filerewrite.WriteLine("//wiimote alone left");
                filerewrite.WriteLine(line53);
                filerewrite.WriteLine("//wiimote alone right");
                filerewrite.WriteLine(line54);
                filerewrite.WriteLine("//wiimote alone 1");
                filerewrite.WriteLine(line55);
                filerewrite.WriteLine("//wiimote alone 2");
                filerewrite.WriteLine(line56);
                filerewrite.WriteLine("//wiimote nunchuck roll right");
                filerewrite.WriteLine(line57);
                filerewrite.WriteLine("//wiimote nunchuck roll left");
                filerewrite.WriteLine(line58);
                filerewrite.WriteLine("//wiimote to front");
                filerewrite.WriteLine(line59);
                filerewrite.WriteLine("//nunchuck to down");
                filerewrite.WriteLine(line60);
                filerewrite.WriteLine("//nunchuck to down");
                filerewrite.WriteLine(line61);
                filerewrite.WriteLine("//nunchuck to down");
                filerewrite.WriteLine(line62);
                filerewrite.WriteLine("//nunchuck z and c");
                filerewrite.WriteLine(line63);
                filerewrite.WriteLine("//nunchuck c");
                filerewrite.WriteLine(line64);
                filerewrite.WriteLine("//nunchuck z");
                filerewrite.WriteLine(line65);
                filerewrite.WriteLine("//wiimote nunchuck down");
                filerewrite.WriteLine(line66);
                filerewrite.WriteLine("//wiimote nunchuck home");
                filerewrite.WriteLine(line67);
                filerewrite.WriteLine("//wiimote nunchuck left");
                filerewrite.WriteLine(line68);
                filerewrite.WriteLine("//wiimote nunchuck right");
                filerewrite.WriteLine(line69);
                filerewrite.WriteLine("//wiimote nunchuck up");
                filerewrite.WriteLine(line70);
                filerewrite.WriteLine("//wiimote nunchuck 1");
                filerewrite.WriteLine(line71);
                filerewrite.WriteLine("//wiimote nunchuck 2");
                filerewrite.WriteLine(line72);
                filerewrite.WriteLine("//angleinit");
                filerewrite.WriteLine(line73);
                filerewrite.WriteLine("//irxinit");
                filerewrite.WriteLine(line74);
                filerewrite.WriteLine("//iryinit");
                filerewrite.WriteLine(line75);
                filerewrite.WriteLine("//wiimote to front push r time extra setting");
                filerewrite.WriteLine(line76);
                filerewrite.WriteLine("//double A push r time extra setting");
                filerewrite.WriteLine(line77);
                filerewrite.WriteLine("//cancel reload waiting A or C time extra setting");
                filerewrite.WriteLine(line78);
                filerewrite.WriteLine("//second nunchuck to down push v time extra setting");
                filerewrite.WriteLine(line79);
                filerewrite.WriteLine("//brink or titanfall time extra setting");
                filerewrite.WriteLine(line80);
                filerewrite.WriteLine("//bo3 time extra setting");
                filerewrite.WriteLine(line81);
                filerewrite.WriteLine("//smooth time extra setting");
                filerewrite.WriteLine(line82);
                filerewrite.WriteLine("//aim plus latency time extra setting");
                filerewrite.WriteLine(line83);
                filerewrite.WriteLine("//aim plus quantity extra setting");
                filerewrite.WriteLine(line84);
                filerewrite.WriteLine("//anti-tearing outer size");
                filerewrite.WriteLine(line85);
                filerewrite.WriteLine("//hardness quantity");
                filerewrite.WriteLine(line86);
                filerewrite.WriteLine("//aim speed axis x quantity");
                filerewrite.WriteLine(line87);
                filerewrite.WriteLine("//aim speed axis y quantity");
                filerewrite.WriteLine(line88);
                filerewrite.WriteLine("//aim speed accuracy size of center axis x extra setting");
                filerewrite.WriteLine(line89);
                filerewrite.WriteLine("//aim speed accuracy multipler of center axis x extra setting");
                filerewrite.WriteLine(line90);
                filerewrite.WriteLine("//aim speed accuracy size of center axis y extra setting");
                filerewrite.WriteLine(line91);
                filerewrite.WriteLine("//aim speed accuracy multipler of center axis y extra setting");
                filerewrite.WriteLine(line92);
                filerewrite.WriteLine("//no recoil quantity extra setting");
                filerewrite.WriteLine(line93);
                filerewrite.WriteLine("//1 tab switch interval time extra setting");
                filerewrite.WriteLine(line94);
                filerewrite.WriteLine("//1 tab switch press delay time extra setting");
                filerewrite.WriteLine(line95);
                filerewrite.WriteLine("//tick time");
                filerewrite.WriteLine(line96);
                filerewrite.WriteLine("//wheel script stick limit in");
                filerewrite.WriteLine(line97);
                filerewrite.WriteLine("//wheel script stick limit out");
                filerewrite.WriteLine(line98);
                filerewrite.WriteLine("//wheel script gyroscope limit in");
                filerewrite.WriteLine(line99);
                filerewrite.WriteLine("//wheel script gyroscope limit out");
                filerewrite.WriteLine(line100);
                filerewrite.WriteLine("//zoning quantity");
                filerewrite.WriteLine(line101);
                filerewrite.WriteLine("//zoning hardness quantity");
                filerewrite.WriteLine(line102);
                filerewrite.WriteLine("//no recoil step quantity");
                filerewrite.WriteLine(line103);
                filerewrite.WriteLine("//slide init");
                filerewrite.WriteLine(line104);
                filerewrite.WriteLine("//slide time");
                filerewrite.WriteLine(line105);
                filerewrite.WriteLine("//possible entries");
                filerewrite.WriteLine("WASD, ZQSD, arrow keys, AD, QD, left right arrow keys, A, B, C, D, E, ..., X, Y, Z, 0, 1, 2, ..., 8, 9, F1, F2, F3, ..., F11,");
                filerewrite.WriteLine("F12, Capslock, Alt, Back, Apostrophe, left, right, up, down, Escape, Control, LControl, RControl, Shift, LShift, RShift,");
                filerewrite.WriteLine("Enter, Space, Tab, wheel down, wheel up, middle click, left click, right click, 0-4, 5-9, Enter/Tab.");
                filerewrite.Close();
            }
        }
    }
}
